// GAMES
export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';

// ROUTER
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// GAME
export const FETCH_GAME_SCREENSHOTS_SUCCESS = 'FETCH_GAME_SCREENSHOTS_SUCCESS';

// APP
export const PLAY_FULL_VIDEO = 'PLAY_FULL_VIDEO';
export const CLOSE_FULL_VIDEO = 'CLOSE_FULL_VIDEO';
export const WINDOW_RESIZE = 'WINDOW_RESIZE';

// USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_USER = 'CLEAR_USER';
