export const GENRE_COLLECTION_TYPE = 'GENRE_COLLECTION_TYPE';
export const SEARCH_COLLECTION_TYPE = 'GENRE_COLLECTION_TYPE';
export const TAG_COLLECTION_TYPE = 'TAG_COLLECTION_TYPE';

export const GAME_COLLECTION_TYPE = 'GAME_COLLECTION_TYPE';
